# Generated by Django 4.0.4 on 2022-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blank_null_true_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='blank_true_field',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='person',
            name='null_true_field',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
