# Generated by Django 4.0.4 on 2022-05-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0002_person_blank_null_true_field_person_blank_true_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankNullModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('not_null_not_blank', models.CharField(max_length=1)),
                ('null', models.CharField(max_length=1, null=True)),
                ('blank', models.CharField(blank=True, max_length=1)),
                ('blank_null', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='blank_null_true_field',
        ),
        migrations.RemoveField(
            model_name='person',
            name='blank_true_field',
        ),
        migrations.RemoveField(
            model_name='person',
            name='null_true_field',
        ),
    ]
