# Generated by Django 4.0.4 on 2022-05-28 17:27

from django.db import migrations, models
import models_tutorial.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0003_blanknullmodel_remove_person_blank_null_true_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(default='TEST', max_length=10)),
                ('default_callable', models.CharField(default=models_tutorial.models.default_callable_f, max_length=10)),
                ('default_various_callable', models.IntegerField(default=models_tutorial.models.default_various_callable_f)),
            ],
        ),
    ]
