# Generated by Django 4.0.4 on 2022-05-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0004_defaultmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_column', models.CharField(help_text='Обычное строковое поле', max_length=100)),
                ('int_column', models.IntegerField(help_text='Обычное числовое поле')),
                ('date_column', models.DateField(help_text='Обычное поле дата')),
            ],
        ),
    ]
