# Generated by Django 4.0.4 on 2022-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0005_helptextmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkModel',
            fields=[
                ('pk_column', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('char_column', models.CharField(max_length=100)),
            ],
        ),
    ]
