# Generated by Django 4.0.4 on 2022-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_tutorial', '0007_uniquemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerboseNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('without_description', models.IntegerField()),
                ('with_description', models.IntegerField(verbose_name='field with description')),
                ('with_verbose_name', models.IntegerField(verbose_name='column with verbose name')),
            ],
        ),
    ]
