# Generated by Django 4.0.4 on 2022-08-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_rare_flg', models.BooleanField()),
                ('is_hunter_flg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogOneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_one', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogOneModelWithMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_one', models.TextField()),
            ],
            options={
                'db_table': 'catalog_one"."postprocess_catalogonemodelwithmeta',
            },
        ),
        migrations.CreateModel(
            name='CatalogTwoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CatalogTwoModelWithMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_two', models.TextField()),
            ],
            options={
                'db_table': 'catalog_two"."postprocess_catalogtwomodelwithmeta',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShelterStgDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ShelterStg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DogStgDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DogStg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('shelter', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postprocess.breed')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postprocess.shelter')),
            ],
        ),
        migrations.CreateModel(
            name='BreedStgDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BreedStg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dml_operation_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_rare_flg', models.BooleanField()),
                ('is_hunter_flg', models.BooleanField()),
            ],
            options={
                'unique_together': {('dml_operation_id', 'name')},
            },
        ),
    ]
