# Generated by Django 4.0.4 on 2022-05-23 20:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=1000, overwrite=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=1000, overwrite=True, populate_from=('name', 'surname'), unique=True)),
                ('house_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_nested_url.house')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('purchase_date', models.DateField()),
                ('price', models.IntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=1000, overwrite=True, populate_from=('model', 'purchase_date'), unique=True)),
                ('human_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_nested_url.human')),
            ],
            options={
                'unique_together': {('model', 'purchase_date')},
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=1000, overwrite=True, populate_from=('name', 'surname', 'phone_number'), unique=True)),
                ('phone_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_nested_url.phone')),
            ],
        ),
    ]
