# Generated by Django 4.0.4 on 2022-05-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_nested_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name', 'surname', 'phone_number')},
        ),
    ]
