# Generated by Django 4.0.4 on 2022-05-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
