# Generated by Django 4.0.4 on 2022-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=128, null=True, verbose_name='Пользователь, создавший запись')),
                ('created_dt', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('created_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи')),
                ('modified_by', models.CharField(max_length=128, null=True, verbose_name='Пользователь, создавший запись')),
                ('modified_dt', models.DateField(auto_now=True, verbose_name='Дата создания записи')),
                ('modified_dttm', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания записи')),
                ('food_name', models.CharField(max_length=300, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена блюда')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
