# Generated by Django 4.0.4 on 2022-06-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_and_scd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTogetherSingleFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=100, unique=True)),
                ('name_2', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name_2',), ('name_1', 'name_2'), ('name_1',)},
            },
        ),
    ]
